version = 1

[[analyzers]]
<< deepsource-config-dc794d08
name = "secrets"

<< deepsource-config-bc693d3d
name = "cxx"

<< deepsource-config-35ef329a
name = "javascript"
name = "secrets"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "angular"
  ]
  environment = [
    "nodejs",
    "mongo"
  ]

[[transformers]]
name = "prettier"
>> master
>> master
>> master
